# Generated by Django 4.0.8 on 2023-10-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_qty',
            new_name='students_qty',
        ),
    ]
